spring:
  datasource:
    url: jdbc:mysql://www.alexyan.cn:3306/aspirin?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xyyj1982

server:
  port: 8090

# 扫描Mapper接口文件的配置在 config.MybatisConfig
# 扫描实体类的位置
mybatis:
  type-aliases-package: com.hubu.aspirin.model.entity

logging:
  file:
    name: /home/apps/aspirin/app.log  # 日志文件的地址
#  level:
#    root: debug

# 扫描Mapper.xml的位置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    # 默认枚举处理器, 省略扫描通用枚举配置
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

# knife4j中自定义文档的位置 (文件名只能以.md结尾)
knife4j.markdowns: classpath:/markdown/*

# actuator 配置
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
info: # 自定义 actuator info字段
  app-name: aspirin
  author: alex
  email: xxxxx@gmail.com
